// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApi.Data;

#nullable disable

namespace StudentApi.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    partial class StorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleCases", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "CaseId")
                        .HasName("PK_ArticleCases");

                    b.HasIndex("CaseId");

                    b.ToTable("ArticleCases", (string)null);
                });

            modelBuilder.Entity("StudentApi.Models.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("user");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK_AppUsers");

                    b.HasIndex(new[] { "Username" }, "UQ_AppUsers_Username")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullLocation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NomArticle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Seuil")
                        .HasColumnType("int");

                    b.HasKey("ArticleId")
                        .HasName("PK_Articles");

                    b.HasIndex(new[] { "CodeArticle" }, "UQ_Articles_CodeArticle")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<int>("CapaciteMaximum")
                        .HasColumnType("int");

                    b.Property<string>("CodeCase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PositionCase")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Disponible");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("CaseId")
                        .HasName("PK_Cases");

                    b.HasIndex(new[] { "ZoneId", "CodeCase" }, "UQ_Cases_Zone_Code")
                        .IsUnique();

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Donnee", b =>
                {
                    b.Property<int>("DonneeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonneeId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Mois")
                        .HasColumnType("date");

                    b.Property<int>("QuantiteEntrer")
                        .HasColumnType("int");

                    b.Property<int>("QuantiteSortie")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Manuel");

                    b.HasKey("DonneeId")
                        .HasName("PK_Donnees");

                    b.HasIndex("CaseId");

                    b.HasIndex(new[] { "ArticleId", "CaseId", "Mois" }, "UQ_Donnees_Article_Case_Mois")
                        .IsUnique()
                        .HasFilter("[CaseId] IS NOT NULL");

                    b.HasIndex(new[] { "ArticleId", "Mois" }, "UQ_Donnees_Legacy_Article_Mois")
                        .IsUnique()
                        .HasFilter("[CaseId] IS NULL");

                    b.ToTable("Donnees");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Magasin", b =>
                {
                    b.Property<int>("MagasinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MagasinId"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodeMagasin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NomMagasin")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MagasinId")
                        .HasName("PK_Magasins");

                    b.HasIndex(new[] { "CodeMagasin" }, "UQ_Magasins_CodeMagasin")
                        .IsUnique();

                    b.ToTable("Magasins");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Rayon", b =>
                {
                    b.Property<int>("RayonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RayonId"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodeRayon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MagasinId")
                        .HasColumnType("int");

                    b.Property<string>("NomRayon")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("RayonId")
                        .HasName("PK_Rayons");

                    b.HasIndex(new[] { "MagasinId", "CodeRayon" }, "UQ_Rayons_Magasin_Code")
                        .IsUnique();

                    b.ToTable("Rayons");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NumeroLigne")
                        .HasColumnType("int");

                    b.Property<int>("RayonId")
                        .HasColumnType("int");

                    b.HasKey("ZoneId")
                        .HasName("PK_Zones");

                    b.HasIndex(new[] { "RayonId", "CodeZone" }, "UQ_Zones_Rayon_Code")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("ArticleCases", b =>
                {
                    b.HasOne("StudentApi.Models.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleCases_Articles");

                    b.HasOne("StudentApi.Models.Entities.Case", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleCases_Cases");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Case", b =>
                {
                    b.HasOne("StudentApi.Models.Entities.Zone", "Zone")
                        .WithMany("Cases")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Zones");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Donnee", b =>
                {
                    b.HasOne("StudentApi.Models.Entities.Article", "Article")
                        .WithMany("Donnees")
                        .HasForeignKey("ArticleId")
                        .IsRequired()
                        .HasConstraintName("FK_Donnees_Articles");

                    b.HasOne("StudentApi.Models.Entities.Case", "Case")
                        .WithMany("Donnees")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Donnees_Cases");

                    b.Navigation("Article");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Rayon", b =>
                {
                    b.HasOne("StudentApi.Models.Entities.Magasin", "Magasin")
                        .WithMany("Rayons")
                        .HasForeignKey("MagasinId")
                        .IsRequired()
                        .HasConstraintName("FK_Rayons_Magasins");

                    b.Navigation("Magasin");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Zone", b =>
                {
                    b.HasOne("StudentApi.Models.Entities.Rayon", "Rayon")
                        .WithMany("Zones")
                        .HasForeignKey("RayonId")
                        .IsRequired()
                        .HasConstraintName("FK_Zones_Rayons");

                    b.Navigation("Rayon");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Article", b =>
                {
                    b.Navigation("Donnees");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Case", b =>
                {
                    b.Navigation("Donnees");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Magasin", b =>
                {
                    b.Navigation("Rayons");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Rayon", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("StudentApi.Models.Entities.Zone", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
